config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }
  root 'entries#index'
  resources :admins, only: [:index, :show, :edit, :update]
  resources :groups, except: [:show, :destroy] do
    resources :messages, except: [:show]
  end
  resources :users, only: [:index, :show, :edit ,:update] do
    collection {get "search"}
    resources :entries, only: [:index]
  end
  resources :entries, only: [:index, :show, :new, :create, :edit] do
    collection {get "job_category_search"}
    collection {get "all_search"}
  end
end

app/views/admins/edit.html.erb
<div class="body_ya">
  <div class="post_head">
    <h2>マイページ編集</h2>
  </div>
  <%= form_for @admin do |f| %>
    <%= f.label :image do %>
      <%= f.file_field :image, style: "display: none;" %>
      <img src="/assets/blank_icon.jpg" class="student_upload_image">
    <% end %>

    <div class="student_profile">
      <%= f.label :名前, class: "form_label" %>
      <%= f.text_field :name, class: "normal-input", placeholder: "株式会社SUKIMA" %>
    </div>

    <div class="student_profile">
      <%= f.label :ウェブサイト, class: "form_label" %>
      <%= f.text_field :web, class: "normal-input", placeholder: "www.sukima.com" %>
    </div>

    <div class="student_profile">
      <%= f.label :所在地, class: "form_label" %>
      <%= f.text_field :address, class: "normal-input", placeholder: "福岡県中央区天神0丁目 0-0" %>
    </div>

    <div class="student_profile">
      <%= f.label :業種, class: "form_label" %>
      <%= f.text_field :industry, class: "normal-input", placeholder: "通信..etc" %>
    </div>

    <div class="student_profile">
      <%= f.label :会社概要説明, class: "form_label" %>
      <div class="triangle"></div>
      <%= f.text_area :about, class: "student_introduce" %>
    </div>

    <div class="post_in">
      <%= f.submit "登録する", class: "input_btn" %>
    </div>
  <% end %>
</div>

app/views/admins/index.html.erb
<% provide(:title, 'All admins') %>
<h1>All companies</h1>
 
<ul class="admins">
  <% @admins.each do |admin| %>
    <li>
      <%= link_to admin.name, admin %>
    </li>
  <% end %>
</ul>

app/views/admins/show.html.erb
<div class="profile">
  <div class="post_head">
    <img class="title" src="/assets/mypage_kotoba.png">
  </div>
  <div class="student_image">
    <%= image_tag @admin.image %>
  </div>
  <div class="post_head">
    <h2><%= @admin.name %></h2>
  </div>
  <table class="companies">
    <tr>
      <th>会社名</th>
      <td><%= @admin.name %></td>
    </tr>

    <tr>
      <th>ウェブサイト</th>
      <td><%= link_to @admin.web, @admin.web %></td>
    </tr>

    <tr>
      <th>所在地</th>
      <td><%= @admin.address %></td>
    </tr>

    <tr>
      <th>業種</th>
      <td><%= @admin.industry %></td>
    </tr>

    <tr>
      <th>会社概要</th>
      <td><%= @admin.about %></td>
    </tr>

  </table>
  <p><%= link_to 'プロフィール変更', edit_admin_path %></p>
</div>