config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }
  root 'entries#index'
  resources :admins, only: [:index, :show, :edit, :update]
  resources :groups, except: [:show, :destroy] do
    resources :messages, except: [:show]
  end
  resources :users, only: [:index, :show, :edit ,:update] do
    collection {get "search"}
    resources :entries, only: [:index]
  end
  resources :entries, only: [:index, :show, :new, :create, :edit] do
    collection {get "job_category_search"}
    collection {get "all_search"}
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  
  class << self
    def search(query)
      rel = order("created_at DESC")
      if query.present?
        rel = rel.where("title LIKE", "%#{query}%", "%#{query}%")
      end
      rel
    end
  end

  has_many :groups
  belongs_to :user
  # belongs_to :author, class_name:"User", foreign_key: "user_id"

  # STATUS_VALUES = %w(draft user_only public)

  validates :title, presence: true, length: {maximum: 200}
  # validates :status, inclusion: { in:STATUS_VALUES }

  mount_uploader :image, ImageUploader

  # scope :common, -> { where(status:"public") }
  # scope :published, -> { where("status <> ?","draft")}
  # scope :full, -> (user) { where("status <> ? OR user_id = ?", "draft", user.id) }
  # scope :readable_for, ->(user) { user ? full(user) : common }

  # class << self
  #   def status_text(status)
  #     I18n.t("activerecord.attributes.entry.status_#{status}")
  #   end

  #   def status_options
  #     STATUS_VALUES.map { |status| [status_text(status), status] }
  #   end

  #   def sidebar_entries(user, num = 5)
  #     readable_for(user).order(posted_at::desc).limit(num)
  #   end
  # end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]

  def index
    if params[:id]
      @user = User.find(params[:id])
      @entries = @user.entries.page(params[:page]).per(3)
    else
      @entries = Entry.all.page(params[:page]).per(3)
    end
    @entries = @entries.order("created_at DESC").page(params[:page]).per(3)
    @group = Group.new
    # @entries = @entries.readable_for(current_user).order(posted_at: :desc)#.paginate(page: params[:page], per_page: 5)
  end

  def show
    @entry = Entry.find(params[:id])
    # @entry = Entry.readable_for(current_user).find(params[:id])
    @group = Group.new(user_id: @entry.user_id)
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = current_user.entries.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)
    # @entry.author = current_user
    if @entry.save
      redirect_to root_path, notice:"投稿を作成しました"
    else
      render "new"
    end
 end

  def update
    @entry = current_user.entries.find(params[:id])
    @entry.assign_attributes(entry_params)
    if @entry.save
      redirect_to @entry, notice:"投稿を更新しました"
    else
      render "edit"
    end
  end

   def destroy
    @entry = current_user.entries.find(params[:id])
      @entry.destroy
      redirect_to :entries, notice:"投稿を削除しました"
    end


  def job_category_search
    @entries = Entry.where('job_category LIKE(?)', "%#{params[:keyword]}%").page(params[:page]).per(3)
    render "index"
  end

  def all_search
    @q = Entry.ransack(params[:q])
    @entries = @q.result(distinct: true).page(params[:page]).per(3)
    render "index"
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :body, :job_category).merge(user_id: current_user.id)
    end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_footer.html.erb
<p class="article_footer">
    <% if current_user %>
    <!--<= Entry.status_text(entry.status) %> |-->
    <% if current_user == @entry.author %>
    <%= link_to "編集", [:edit, @entry] %> |
    <%= link_to "削除", @enrty, method: :delete, data: { confirm: "本当に削除しますか？" } %> |
    <% end %>
    <% end %>
    by <%= link_to @entry.author.name, @entry.author  %> |
    <%= @entry.posted_at.strftime("%Y/%m/%d %H:%M") %>
</p>

app/views/entries/edit.html.erb
<h3>投稿の編集</h3>

<p><%= link_to "投稿の詳細に戻る", @entry %></p>

<%= form_for @entry do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/entries/index.html.erb
  <div class="category_search sp">
    <div class="category_btn">
      <img src="./assets/cat_search_on.png" class="cat_search_on">
      <img src="./assets/cat_search_off.png" class="cat_search_off hidden">
    </div>

    <div class="category_content" style="display: none;">
      <%= form_tag('/entries/job_category_search', method: :get) do %>
        <%= button_tag("企画", class: "category_part", name: "keyword", value: "企画") %>
        <%= button_tag("制作", class: "category_part", name: "keyword", value: "制作") %>
        <%= button_tag("事務", class: "category_part", name: "keyword", value: "事務") %>
        <%= button_tag("専門職", class: "category_part", name: "keyword", value: "専門色") %>
        <%= button_tag("営業", class: "category_part", name: "keyword", value: "営業") %>
        <%= button_tag("医療", class: "category_part", name: "keyword", value: "医療") %>
        <%= button_tag("教育", class: "category_part", name: "keyword", value: "教育") %>
        <%= button_tag("エンジニア", class: "category_part", name: "keyword", value: "エンジニア") %>
      <% end %>
      <%= search_form_for @q, url: all_search_entries_path do |f| %>
        <p><%= f.search_field :job_category_or_title_or_area_or_body_cont %>
           <%= submit_tag "検索" %></p>
      <% end %>
      <a href=""><div class="category_btn"><img src="./assets/cat_search.png"></div></a>
    </div>
  </div>

  <div class="category_search_pc pc">
    <div class="category_tab">職種</div>
    <div class="category_content_pc">
      <label class="cat_content_part"><%= link_to "営業", job_category_search_entries_path(keyword: "営業") %></label>
      <label class="cat_content_part"><%= link_to "事務", job_category_search_entries_path(keyword: "事務") %></label>
      <label class="cat_content_part"><%= link_to "企画", job_category_search_entries_path(keyword: "企画") %></label>
      <label class="cat_content_part"><%= link_to "サービス", job_category_search_entries_path(keyword: "サービス") %></label>
      <label class="cat_content_part"><%= link_to "制作", job_category_search_entries_path(keyword: "制作") %></label>
      <label class="cat_content_part"><%= link_to "クリエイティブ", job_category_search_entries_path(keyword: "クリエイティブ") %></label>
      <label class="cat_content_part"><%= link_to "専門職", job_category_search_entries_path(keyword: "専門職") %></label>
      <label class="cat_content_part"><%= link_to "ITエンジニア", job_category_search_entries_path(keyword: "ITエンジニア") %></label>
      <label class="cat_content_part"><%= link_to "医療", job_category_search_entries_path(keyword: "医療") %></label>
      <label class="cat_content_part"><%= link_to "教育", job_category_search_entries_path(keyword: "教育") %></label>
    </div>
  </div>



<!-- スマホバージョン -->
<div class="bgcolor post-section">
<% if @entries.present? %>
<div class="posts sp">
  <% @entries.each do |entry| %>
    <div class="post">
      <div class="post_main">
        <div class="post_cat post_cat_dark">
          <!--<img src="./assets/cat_01.png">-->
          <!-- 画像が作成されてないので後ほど反映 -->
          <% if entry.job_category == "営業" %>
            <img src="./assets/cat_02.png">
          <% elsif entry.job_category == "事務" %>
            <img src="./assets/cat_03_officework.png">
          <% elsif entry.job_category == "企画" %>
            <img src="./assets/cat_planning".png>
          <% elsif entry.job_category == "サービス" %>
            <img src="./assets/cat_service.png">
          <% elsif entry.job_category == "制作" %>
            <img src="./assets/cat_production.png">
          <% elsif entry.job_category == "クリエイティブ" %>
            <img src="./assets/cat_01.png">
          <% elsif entry.job_category == "教育" %>
            <img src="./assets/cat_education.png">
          <% elsif entry.job_category == "ITエンジニア" %>
            <img src="./assets/cat_engineer.png">
          <% elsif entry.job_category == "医療" %>
            <img src="./assets/cat_medical.png">
          <% else %>
            <img src="./assets/cat_01.png">
          <% end %>
         </div>
        <div class="user_image">
        <!-- ゆーざーの写真 -->
        <% if !entry.user.image.nil? %>
          <%= link_to image_tag(entry.user.image), user_path(entry.user) %>
        <% else %>
          <%= link_to image_tag('brank_icon.jpg'), user_path(entry.user) %>
        <% end %>
        </div>
        <div class="post_main_text">
          <%= link_to entry.user.name, user_path(entry.user), class: "name" %>
          <h3><%= link_to entry.title, entry_path(entry), class: "entry_title" %></h3>
          <% if admin_signed_in? %>
          <!--<div class="post_chat_btn">
            <p><%= link_to image_tag("chat_btn_phone.png"), entry_path(entry), :class=>'post_chat_btn' %></p>
      <!--class= '-->
          </div>-->
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- PCバージョン -->
<div class="posts pc">
  <% @entries.each do |entry| %>
    <div class="post">
      <div class="post_main">
        <div class="post_cat post_cat_dark">
          <% if entry.job_category == "クリエイティブ" %>
            <img src="./assets/creative.png">
          <% elsif entry.job_category == "教育" %>
            <img src="./assets/kyouiku.png">
          <% elsif entry.job_category == "ITエンジニア" %>
            <img src="./assets/engineer.png">
          <% elsif entry.job_category == "医療" %>
            <img src="./assets/iryou.png">
          <% elsif entry.job_category == "事務" %>
            <img src="./assets/jimu.png">
          <% elsif entry.job_category == "企画" %>
            <img src="./assets/kikaku.png">
          <% elsif entry.job_category == "制作" %>
            <img src="./assets/seisaku.png">
          <% elsif entry.job_category == "営業" %>
            <img src="./assets/eigyo.png">
          <% elsif entry.job_category == "サービス" %>
            <img src="./assets/service.png">
          <% else %>
            <img src="./assets/profession.jpg">
          <% end %>
        </div>
        <div class="test_post_main_title">
          <h3><%= link_to entry.title, entry_path(entry), class: "entry_title" %></h3>
        </div>
        <div class="user_image">
          <%= link_to image_tag(entry.user.image), user_path(entry.user) %>
        </div>
        <div class="post_main_text">
          <p class="name"><%= entry.user.name %></p>
          <%= link_to image_tag('chat_suru_pc.png'), groups_path %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% else %>
<p>会員情報がありません</p>
<% end %>
<!-- /追加分 -->


<!-- ページネーション -->
<%= paginate(@entries) %>
<!--   <nav>
    <ul class="pagination pagination-lg">
      <li><a href="#">&raquo;</a></li>
      <li><a href="#">5</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">2</a></li>
      <li class="active"><a href="#">1</a></li>
      <li class="disabled"><a href="#">&laquo;</a></li>
    </ul>
  </nav>
 -->

 <div class="fixed_post">
   <%= link_to image_tag('toukou.png'), new_entry_path %>
 </div>

</div>

<script type="text/javascript">
  $('.category_btn').click(function () {
    if ($(".cat_search_off").is(":hidden")) {
      $(".cat_search_on").addClass('hidden');
      $(".cat_search_off").removeClass('hidden');
      $(".category_content").slideDown("slow");
    } else {
      $(".cat_search_on").removeClass('hidden');
      $(".cat_search_off").addClass('hidden');
      $(".category_content").slideUp("slow");
    }
  });
</script>

app/views/entries/new.html.erb
<h2 class="post_theme">投稿フォーム</h2>
<%= form_for @entry do |f| %>
  <div class="title-block">
    <div><%= f.label :title, class: "entry_label" %></div>
    <div><%= f.text_field :title, class: "title_input" %></div>
  </div>
  <div class="body-block">
    <div><%= f.label :body, class: "entry_label" %></div>
    <div><%= f.text_area :body, class: "body_input", rows: "10" %></div>
  </div>
  <%= f.label :職種, class: "entry_label"%>
  <div class="job_category">
    <label class="job_cat_btn"><%= f.radio_button :job_category, "営業" %><img src="/assets/sales.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "企画" %><img src="/assets/planning.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "制作" %><img src="/assets/production.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "ITエンジニア" %><img src="/assets/enginieer.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "医療" %><img src="/assets/medical.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "事務" %><img src="/assets/officework.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "クリエイティブ" %><img src="/assets/creative.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "教育" %><img src="/assets/education.jpg"></label>
    <label class="job_cat_btn"><%= f.radio_button :job_category, "サービス" %><img src="/assets/service.jpg"></label>
  </div>
  <%= image_submit_tag("/assets/toukou2_off.png", class: 'post_submit_btn')%>
<% end %>

app/views/entries/show.html.erb
<%= image_tag @entry.user.image, height: "70", width: "70" ,class: "entry_image" %>
<div class="entry_text">
  <h4><%= @entry.user.name %></h4>
  <h3><%= @entry.title %></h3>
  <div class="student_profile">
    <!--<div class="triangle"></div>-->
    <div class="entry_words"><%= simple_format(@entry.body) %></div>
  </div>
<% unless current_user.nil? %>
  <% if current_user.id == @entry.user_id %>
    <p><%= link_to "編集", [:edit, @entry] %></p>
  <% end %>
<% end %>
</div>

<!--<% if admin_signed_in? %>-->
  <%= form_for @group do |f| %>
    <div class="button">
      <%= f.hidden_field :user_id, user_id: @group.id %>
      <%= button_tag type: :submit do %>
        <%= image_tag "chat_suru.png" %>
      <% end %>
    </div>
  <% end %>
<!--<% end %>-->